### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by zylwithxy** [SmallDoges/flash-dmattn#150]
Hi authors,

I followed the installation steps and encountered the following problems.
RuntimeError: CUDA flash_dmattn_func is not available. Please check the installation.

**Comment by LoserCheems** [comment]
Hi @zylwithxy, could you please post the installation log? 

I suspect you might have encountered the same issue as #149, but this problem has been fixed,
You can try pulling the latest changes to give it a try.🤗

**Comment by zylwithxy** [comment]
> Hi [@zylwithxy](https://github.com/zylwithxy), could you please post the installation log?
> 
> I suspect you might have encountered the same issue as [#149](https://github.com/SmallDoges/flash-dmattn/pull/149), but this problem has been fixed, You can try pulling the latest changes to give it a try.🤗

`Using pip 25.2 from /venv/main/lib/python3.10/site-packages/pip (python 3.10)
Processing /workspace/cvpr2026/head_efficient/attn_speed/flash-dmattn
  Preparing metadata (pyproject.toml): started
  Running command Preparing metadata (pyproject.toml)


  torch.__version__  = 2.8.0+cu126


  /venv/main/lib/python3.10/site-packages/setuptools/config/_apply_pyprojecttoml.py:82: SetuptoolsDeprecationWarning: `project.license` as a TOML table is deprecated
  !!

          ********************************************************************************
          Please use a simple string containing a SPDX expression for `project.license`. You can also use `project.license-files`. (Both options available on setuptools>=77.0.0).

          By 2026-Feb-18, you need to update your project and remove deprecated calls
          or your builds will no longer be supported.

          See https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#license for details.
          ********************************************************************************

  !!
    corresp(dist, value, root_dir)
  /venv/main/lib/python3.10/site-packages/setuptools/config/_apply_pyprojecttoml.py:61: SetuptoolsDeprecationWarning: License classifiers are deprecated.
  !!

          ********************************************************************************
          Please consider removing the following classifiers in favor of a SPDX license expression:

          License :: OSI Approved :: BSD License

          See https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#license for details.
          ********************************************************************************

  !!
    dist._finalize_license_expression()
  /venv/main/lib/python3.10/site-packages/setuptools/dist.py:759: SetuptoolsDeprecationWarning: License classifiers are deprecated.
  !!

          ********************************************************************************
          Please consider removing the following classifiers in favor of a SPDX license expression:

          License :: OSI Approved :: BSD License

          See https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#license for details.
          ********************************************************************************

  !!
    self._finalize_license_expression()
  running dist_info
  creating /tmp/pip-modern-metadata-1e4ka6ds/flash_dmattn.egg-info
  writing /tmp/pip-modern-metadata-1e4ka6ds/flash_dmattn.egg-info/PKG-INFO
  writing dependency_links to /tmp/pip-modern-metadata-1e4ka6ds/flash_dmattn.egg-info/dependency_links.txt
  writing requirements to /tmp/pip-modern-metadata-1e4ka6ds/flash_dmattn.egg-info/requires.txt
  writing top-level names to /tmp/pip-modern-metadata-1e4ka6ds/flash_dmattn.egg-info/top_level.txt
  writing manifest file '/tmp/pip-modern-metadata-1e4ka6ds/flash_dmattn.egg-info/SOURCES.txt'
  reading manifest file '/tmp/pip-modern-metadata-1e4ka6ds/flash_dmattn.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  warning: no files found matching '*.cu' under directory 'src'
  warning: no files found matching '*.h' under directory 'src'
  warning: no files found matching '*.cuh' under directory 'src'
  warning: no files found matching '*.cpp' under directory 'src'
  warning: no files found matching '*.hpp' under directory 'src'
  adding license file 'LICENSE'
  adding license file 'AUTHORS'
  writing manifest file '/tmp/pip-modern-metadata-1e4ka6ds/flash_dmattn.egg-info/SOURCES.txt'
  creating '/tmp/pip-modern-metadata-1e4ka6ds/flash_dmattn-1.0.0.dist-info'
  Preparing metadata (pyproject.toml): finished with status 'done'
Requirement already satisfied: torch in /venv/main/lib/python3.10/site-packages (from flash-dmattn==1.0.0) (2.8.0+cu126)
Requirement already satisfied: einops in /venv/main/lib/python3.10/site-packages (from flash-dmattn==1.0.0) (0.8.1)
Requirement already satisfied: filelock in /venv/main/lib/python3.10/site-packages (from torch->flash-dmattn==1.0.0) (3.18.0)
Requirement already satisfied: typing-extensions>=4.10.0 in /venv/main/lib/python3.10/site-packages (from torch->flash-dmattn==1.0.0) (4.14.0)
Requirement already satisfied: sympy>=1.13.3 in /venv/main/lib/python3.10/site-packages (from torch->flash-dmattn==1.0.0) (1.13.3)
Requirement already satisfied: networkx in /venv/main/lib/python3.10/site-packages (from torch->flash-dmattn==1.0.0) (3.3)
Requirement already satisfied: jinja2 in /venv/main/lib/python3.10/site-packages (from torch->flash-dmattn==1.0.0) (3.1.4)
Requirement already satisfied: fsspec in /venv/main/lib/python3.10/site-packages (from torch->flash-dmattn==1.0.0) (2025.5.1)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.6.77 in /venv/main/lib/python3.10/site-packages (from torch->flash-dmattn==1.0.0) (12.6.77)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.6.77 in /venv/main/lib/python3.10/site-packages (from torch->flash-dmattn==1.0.0) (12.6.77)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.6.80 in /venv/main/lib/python3.10/site-packages (from torch->flash-dmattn==1.0.0) (12.6.80)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /venv/main/lib/python3.10/site-packages (from torch->flash-dmattn==1.0.0) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.6.4.1 in /venv/main/lib/python3.10/site-packages (from torch->flash-dmattn==1.0.0) (12.6.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.0.4 in /venv/main/lib/python3.10/site-packages (from torch->flash-dmattn==1.0.0) (11.3.0.4)
Requirement already satisfied: nvidia-curand-cu12==10.3.7.77 in /venv/main/lib/python3.10/site-packages (from torch->flash-dmattn==1.0.0) (10.3.7.77)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.1.2 in /venv/main/lib/python3.10/site-packages (from torch->flash-dmattn==1.0.0) (11.7.1.2)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.4.2 in /venv/main/lib/python3.10/site-packages (from torch->flash-dmattn==1.0.0) (12.5.4.2)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /venv/main/lib/python3.10/site-packages (from torch->flash-dmattn==1.0.0) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.3 in /venv/main/lib/python3.10/site-packages (from torch->flash-dmattn==1.0.0) (2.27.3)
Requirement already satisfied: nvidia-nvtx-cu12==12.6.77 in /venv/main/lib/python3.10/site-packages (from torch->flash-dmattn==1.0.0) (12.6.77)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.6.85 in /venv/main/lib/python3.10/site-packages (from torch->flash-dmattn==1.0.0) (12.6.85)
Requirement already satisfied: nvidia-cufile-cu12==1.11.1.6 in /venv/main/lib/python3.10/site-packages (from torch->flash-dmattn==1.0.0) (1.11.1.6)
Requirement already satisfied: triton==3.4.0 in /venv/main/lib/python3.10/site-packages (from torch->flash-dmattn==1.0.0) (3.4.0)
Requirement already satisfied: setuptools>=40.8.0 in /venv/main/lib/python3.10/site-packages (from triton==3.4.0->torch->flash-dmattn==1.0.0) (80.9.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /venv/main/lib/python3.10/site-packages (from sympy>=1.13.3->torch->flash-dmattn==1.0.0) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /venv/main/lib/python3.10/site-packages (from jinja2->torch->flash-dmattn==1.0.0) (2.1.5)
Building wheels for collected packages: flash-dmattn
  Building wheel for flash-dmattn (pyproject.toml): started
  Running command Building wheel for flash-dmattn (pyproject.toml)


  torch.__version__  = 2.8.0+cu126


  /venv/main/lib/python3.10/site-packages/setuptools/config/_apply_pyprojecttoml.py:82: SetuptoolsDeprecationWarning: `project.license` as a TOML table is deprecated
  !!

          ********************************************************************************
          Please use a simple string containing a SPDX expression for `project.license`. You can also use `project.license-files`. (Both options available on setuptools>=77.0.0).

          By 2026-Feb-18, you need to update your project and remove deprecated calls
          or your builds will no longer be supported.

          See https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#license for details.
          ********************************************************************************

  !!
    corresp(dist, value, root_dir)
  /venv/main/lib/python3.10/site-packages/setuptools/config/_apply_pyprojecttoml.py:61: SetuptoolsDeprecationWarning: License classifiers are deprecated.
  !!

          ********************************************************************************
          Please consider removing the following classifiers in favor of a SPDX license expression:

          License :: OSI Approved :: BSD License

          See https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#license for details.
          ********************************************************************************

  !!
    dist._finalize_license_expression()
  /venv/main/lib/python3.10/site-packages/setuptools/dist.py:759: SetuptoolsDeprecationWarning: License classifiers are deprecated.
  !!

          ********************************************************************************
          Please consider removing the following classifiers in favor of a SPDX license expression:

          License :: OSI Approved :: BSD License

          See https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#license for details.
          ********************************************************************************

  !!
    self._finalize_license_expression()
  running bdist_wheel
  running build
  running build_py
  copying flash_dmattn/__init__.py -> build/lib.linux-x86_64-cpython-310/flash_dmattn
  copying flash_dmattn/flash_dmattn_flex.py -> build/lib.linux-x86_64-cpython-310/flash_dmattn
  copying flash_dmattn/flash_dmattn_interface.py -> build/lib.linux-x86_64-cpython-310/flash_dmattn
  copying flash_dmattn/flash_dmattn_triton.py -> build/lib.linux-x86_64-cpython-310/flash_dmattn
  copying flash_dmattn/integrations/flash_dynamic_mask_attention.py -> build/lib.linux-x86_64-cpython-310/flash_dmattn/integrations
  copying flash_dmattn/integrations/import_utils.py -> build/lib.linux-x86_64-cpython-310/flash_dmattn/integrations
  copying flash_dmattn/integrations/modeling_flash_dynamic_mask_attention_utils.py -> build/lib.linux-x86_64-cpython-310/flash_dmattn/integrations
  running egg_info
  writing flash_dmattn.egg-info/PKG-INFO
  writing dependency_links to flash_dmattn.egg-info/dependency_links.txt
  writing requirements to flash_dmattn.egg-info/requires.txt
  writing top-level names to flash_dmattn.egg-info/top_level.txt
  reading manifest file 'flash_dmattn.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  warning: no files found matching '*.cu' under directory 'src'
  warning: no files found matching '*.h' under directory 'src'
  warning: no files found matching '*.cuh' under directory 'src'
  warning: no files found matching '*.cpp' under directory 'src'
  warning: no files found matching '*.hpp' under directory 'src'
  adding license file 'LICENSE'
  adding license file 'AUTHORS'
  writing manifest file 'flash_dmattn.egg-info/SOURCES.txt'
  copying flash_dmattn/__init__.py -> build/lib.linux-x86_64-cpython-310/flash_dmattn
  copying flash_dmattn/flash_dmattn_flex.py -> build/lib.linux-x86_64-cpython-310/flash_dmattn
  copying flash_dmattn/flash_dmattn_interface.py -> build/lib.linux-x86_64-cpython-310/flash_dmattn
  copying flash_dmattn/flash_dmattn_triton.py -> build/lib.linux-x86_64-cpython-310/flash_dmattn
  running build_ext
  W0906 08:17:11.737000 4707 site-packages/torch/utils/cpp_extension.py:507] The detected CUDA version (12.4) has a minor version mismatch with the version that was used to compile PyTorch (12.6). Most likely this shouldn't be a problem.
  W0906 08:17:11.738000 4707 site-packages/torch/utils/cpp_extension.py:517] There are no g++ version bounds defined for CUDA version 12.4
  building 'flash_dmattn_cuda' extension
  ninja: no work to do.
  g++ -pthread -B /venv/main/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /venv/main/include -fPIC -O2 -isystem /venv/main/include -shared /workspace/cvpr2026/head_efficient/attn_speed/flash-dmattn/build/temp.linux-x86_64-cpython-310/csrc/flash_api.o /workspace/cvpr2026/head_efficient/attn_speed/flash-dmattn/build/temp.linux-x86_64-cpython-310/csrc/src/instantiations/flash_bwd_hdim128_bf16_causal_sm80.o /workspace/cvpr2026/head_efficient/attn_speed/flash-dmattn/build/temp.linux-x86_64-cpython-310/csrc/src/instantiations/flash_bwd_hdim128_bf16_sm80.o /workspace/cvpr2026/head_efficient/attn_speed/flash-dmattn/build/temp.linux-x86_64-cpython-310/csrc/src/instantiations/flash_bwd_hdim128_fp16_causal_sm80.o /workspace/cvpr2026/head_efficient/attn_speed/flash-dmattn/build/temp.linux-x86_64-cpython-310/csrc/src/instantiations/flash_bwd_hdim128_fp16_sm80.o /workspace/cvpr2026/head_efficient/attn_speed/flash-dmattn/build/temp.linux-x86_64-cpython-310/csrc/src/instantiations/flash_bwd_hdim192_bf16_causal_sm80.o /workspace/cvpr2026/head_efficient/attn_speed/flash-dmattn/build/temp.linux-x86_64-cpython-310/csrc/src/instantiations/flash_bwd_hdim192_bf16_sm80.o /workspace/cvpr2026/head_efficient/attn_speed/flash-dmattn/build/temp.linux-x86_64-cpython-310/csrc/src/instantiations/flash_bwd_hdim192_fp16_causal_sm80.o /workspace/cvpr2026/head_efficient/attn_speed/flash-dmattn/build/temp.linux-x86_64-cpython-310/csrc/src/instantiations/flash_bwd_hdim192_fp16_sm80.o /workspace/cvpr2026/head_efficient/attn_speed/flash-dmattn/build/temp.linux-x86_64-cpython-310/csrc/src/instantiations/flash_bwd_hdim256_bf16_causal_sm80.o /workspace/cvpr2026/head_efficient/attn_speed/flash-dmattn/build/temp.linux-x86_64-cpython-310/csrc/src/instantiations/flash_bwd_hdim256_bf16_sm80.o /workspace/cvpr2026/head_efficient/attn_speed/flash-dmattn/build/temp.linux-x86_64-cpython-310/csrc/src/instantiations/flash_bwd_hdim256_fp16_causal_sm80.o /workspace/cvpr2026/head_efficient/attn_speed/flash-dmattn/build/temp.linux-x86_64-cpython-310/csrc/src/instantiations/flash_bwd_hdim256_fp16_sm80.o /workspace/cvpr2026/head_efficient/attn_speed/flash-dmattn/build/temp.linux-x86_64-cpython-310/csrc/src/instantiations/flash_bwd_hdim32_bf16_causal_sm80.o /workspace/cvpr2026/head_efficient/attn_speed/flash-dmattn/build/temp.linux-x86_64-cpython-310/csrc/src/instantiations/flash_bwd_hdim32_bf16_sm80.o /workspace/cvpr2026/head_efficient/attn_speed/flash-dmattn/build/temp.linux-x86_64-cpython-310/csrc/src/instantiations/flash_bwd_hdim32_fp16_causal_sm80.o /workspace/cvpr2026/head_efficient/attn_speed/flash-dmattn/build/temp.linux-x86_64-cpython-310/csrc/src/instantiations/flash_bwd_hdim32_fp16_sm80.o /workspace/cvpr2026/head_efficient/attn_speed/flash-dmattn/build/temp.linux-x86_64-cpython-310/csrc/src/instantiations/flash_bwd_hdim64_bf16_causal_sm80.o /workspace/cvpr2026/head_efficient/attn_speed/flash-dmattn/build/temp.linux-x86_64-cpython-310/csrc/src/instantiations/flash_bwd_hdim64_bf16_sm80.o /workspace/cvpr2026/head_efficient/attn_speed/flash-dmattn/build/temp.linux-x86_64-cpython-310/csrc/src/instantiations/flash_bwd_hdim64_fp16_causal_sm80.o /workspace/cvpr2026/head_efficient/attn_speed/flash-dmattn/build/temp.linux-x86_64-cpython-310/csrc/src/instantiations/flash_bwd_hdim64_fp16_sm80.o /workspace/cvpr2026/head_efficient/attn_speed/flash-dmattn/build/temp.linux-x86_64-cpython-310/csrc/src/instantiations/flash_bwd_hdim96_bf16_causal_sm80.o /workspace/cvpr2026/head_efficient/attn_speed/flash-dmattn/build/temp.linux-x86_64-cpython-310/csrc/src/instantiations/flash_bwd_hdim96_bf16_sm80.o /workspace/cvpr2026/head_efficient/attn_speed/flash-dmattn/build/temp.linux-x86_64-cpython-310/csrc/src/instantiations/flash_bwd_hdim96_fp16_causal_sm80.o /workspace/cvpr2026/head_efficient/attn_speed/flash-dmattn/build/temp.linux-x86_64-cpython-310/csrc/src/instantiations/flash_bwd_hdim96_fp16_sm80.o /workspace/cvpr2026/head_efficient/attn_speed/flash-dmattn/build/temp.linux-x86_64-cpython-310/csrc/src/instantiations/flash_fwd_hdim128_bf16_causal_sm80.o /workspace/cvpr2026/head_efficient/attn_speed/flash-dmattn/build/temp.linux-x86_64-cpython-310/csrc/src/instantiations/flash_fwd_hdim128_bf16_sm80.o /workspace/cvpr2026/head_efficient/attn_speed/flash-dmattn/build/temp.linux-x86_64-cpython-310/csrc/src/instantiations/flash_fwd_hdim128_fp16_causal_sm80.o /workspace/cvpr2026/head_efficient/attn_speed/flash-dmattn/build/temp.linux-x86_64-cpython-310/csrc/src/instantiations/flash_fwd_hdim128_fp16_sm80.o /workspace/cvpr2026/head_efficient/attn_speed/flash-dmattn/build/temp.linux-x86_64-cpython-310/csrc/src/instantiations/flash_fwd_hdim192_bf16_causal_sm80.o /workspace/cvpr2026/head_efficient/attn_speed/flash-dmattn/build/temp.linux-x86_64-cpython-310/csrc/src/instantiations/flash_fwd_hdim192_bf16_sm80.o /workspace/cvpr2026/head_efficient/attn_speed/flash-dmattn/build/temp.linux-x86_64-cpython-310/csrc/src/instantiations/flash_fwd_hdim192_fp16_causal_sm80.o /workspace/cvpr2026/head_efficient/attn_speed/flash-dmattn/build/temp.linux-x86_64-cpython-310/csrc/src/instantiations/flash_fwd_hdim192_fp16_sm80.o /workspace/cvpr2026/head_efficient/attn_speed/flash-dmattn/build/temp.linux-x86_64-cpython-310/csrc/src/instantiations/flash_fwd_hdim256_bf16_causal_sm80.o /workspace/cvpr2026/head_efficient/attn_speed/flash-dmattn/build/temp.linux-x86_64-cpython-310/csrc/src/instantiations/flash_fwd_hdim256_bf16_sm80.o /workspace/cvpr2026/head_efficient/attn_speed/flash-dmattn/build/temp.linux-x86_64-cpython-310/csrc/src/instantiations/flash_fwd_hdim256_fp16_causal_sm80.o /workspace/cvpr2026/head_efficient/attn_speed/flash-dmattn/build/temp.linux-x86_64-cpython-310/csrc/src/instantiations/flash_fwd_hdim256_fp16_sm80.o /workspace/cvpr2026/head_efficient/attn_speed/flash-dmattn/build/temp.linux-x86_64-cpython-310/csrc/src/instantiations/flash_fwd_hdim32_bf16_causal_sm80.o /workspace/cvpr2026/head_efficient/attn_speed/flash-dmattn/build/temp.linux-x86_64-cpython-310/csrc/src/instantiations/flash_fwd_hdim32_bf16_sm80.o /workspace/cvpr2026/head_efficient/attn_speed/flash-dmattn/build/temp.linux-x86_64-cpython-310/csrc/src/instantiations/flash_fwd_hdim32_fp16_causal_sm80.o /workspace/cvpr2026/head_efficient/attn_speed/flash-dmattn/build/temp.linux-x86_64-cpython-310/csrc/src/instantiations/flash_fwd_hdim32_fp16_sm80.o /workspace/cvpr2026/head_efficient/attn_speed/flash-dmattn/build/temp.linux-x86_64-cpython-310/csrc/src/instantiations/flash_fwd_hdim64_bf16_causal_sm80.o /workspace/cvpr2026/head_efficient/attn_speed/flash-dmattn/build/temp.linux-x86_64-cpython-310/csrc/src/instantiations/flash_fwd_hdim64_bf16_sm80.o /workspace/cvpr2026/head_efficient/attn_speed/flash-dmattn/build/temp.linux-x86_64-cpython-310/csrc/src/instantiations/flash_fwd_hdim64_fp16_causal_sm80.o /workspace/cvpr2026/head_efficient/attn_speed/flash-dmattn/build/temp.linux-x86_64-cpython-310/csrc/src/instantiations/flash_fwd_hdim64_fp16_sm80.o /workspace/cvpr2026/head_efficient/attn_speed/flash-dmattn/build/temp.linux-x86_64-cpython-310/csrc/src/instantiations/flash_fwd_hdim96_bf16_causal_sm80.o /workspace/cvpr2026/head_efficient/attn_speed/flash-dmattn/build/temp.linux-x86_64-cpython-310/csrc/src/instantiations/flash_fwd_hdim96_bf16_sm80.o /workspace/cvpr2026/head_efficient/attn_speed/flash-dmattn/build/temp.linux-x86_64-cpython-310/csrc/src/instantiations/flash_fwd_hdim96_fp16_causal_sm80.o /workspace/cvpr2026/head_efficient/attn_speed/flash-dmattn/build/temp.linux-x86_64-cpython-310/csrc/src/instantiations/flash_fwd_hdim96_fp16_sm80.o /workspace/cvpr2026/head_efficient/attn_speed/flash-dmattn/build/temp.linux-x86_64-cpython-310/csrc/src/instantiations/flash_fwd_split_hdim128_bf16_causal_sm80.o /workspace/cvpr2026/head_efficient/attn_speed/flash-dmattn/build/temp.linux-x86_64-cpython-310/csrc/src/instantiations/flash_fwd_split_hdim128_bf16_sm80.o /workspace/cvpr2026/head_efficient/attn_speed/flash-dmattn/build/temp.linux-x86_64-cpython-310/csrc/src/instantiations/flash_fwd_split_hdim128_fp16_causal_sm80.o /workspace/cvpr2026/head_efficient/attn_speed/flash-dmattn/build/temp.linux-x86_64-cpython-310/csrc/src/instantiations/flash_fwd_split_hdim128_fp16_sm80.o /workspace/cvpr2026/head_efficient/attn_speed/flash-dmattn/build/temp.linux-x86_64-cpython-310/csrc/src/instantiations/flash_fwd_split_hdim192_bf16_causal_sm80.o /workspace/cvpr2026/head_efficient/attn_speed/flash-dmattn/build/temp.linux-x86_64-cpython-310/csrc/src/instantiations/flash_fwd_split_hdim192_bf16_sm80.o /workspace/cvpr2026/head_efficient/attn_speed/flash-dmattn/build/temp.linux-x86_64-cpython-310/csrc/src/instantiations/flash_fwd_split_hdim192_fp16_causal_sm80.o /workspace/cvpr2026/head_efficient/attn_speed/flash-dmattn/build/temp.linux-x86_64-cpython-310/csrc/src/instantiations/flash_fwd_split_hdim192_fp16_sm80.o /workspace/cvpr2026/head_efficient/attn_speed/flash-dmattn/build/temp.linux-x86_64-cpython-310/csrc/src/instantiations/flash_fwd_split_hdim256_bf16_causal_sm80.o /workspace/cvpr2026/head_efficient/attn_speed/flash-dmattn/build/temp.linux-x86_64-cpython-310/csrc/src/instantiations/flash_fwd_split_hdim256_bf16_sm80.o /workspace/cvpr2026/head_efficient/attn_speed/flash-dmattn/build/temp.linux-x86_64-cpython-310/csrc/src/instantiations/flash_fwd_split_hdim256_fp16_causal_sm80.o /workspace/cvpr2026/head_efficient/attn_speed/flash-dmattn/build/temp.linux-x86_64-cpython-310/csrc/src/instantiations/flash_fwd_split_hdim256_fp16_sm80.o /workspace/cvpr2026/head_efficient/attn_speed/flash-dmattn/build/temp.linux-x86_64-cpython-310/csrc/src/instantiations/flash_fwd_split_hdim32_bf16_causal_sm80.o /workspace/cvpr2026/head_efficient/attn_speed/flash-dmattn/build/temp.linux-x86_64-cpython-310/csrc/src/instantiations/flash_fwd_split_hdim32_bf16_sm80.o /workspace/cvpr2026/head_efficient/attn_speed/flash-dmattn/build/temp.linux-x86_64-cpython-310/csrc/src/instantiations/flash_fwd_split_hdim32_fp16_causal_sm80.o /workspace/cvpr2026/head_efficient/attn_speed/flash-dmattn/build/temp.linux-x86_64-cpython-310/csrc/src/instantiations/flash_fwd_split_hdim32_fp16_sm80.o /workspace/cvpr2026/head_efficient/attn_speed/flash-dmattn/build/temp.linux-x86_64-cpython-310/csrc/src/instantiations/flash_fwd_split_hdim64_bf16_causal_sm80.o /workspace/cvpr2026/head_efficient/attn_speed/flash-dmattn/build/temp.linux-x86_64-cpython-310/csrc/src/instantiations/flash_fwd_split_hdim64_bf16_sm80.o /workspace/cvpr2026/head_efficient/attn_speed/flash-dmattn/build/temp.linux-x86_64-cpython-310/csrc/src/instantiations/flash_fwd_split_hdim64_fp16_causal_sm80.o /workspace/cvpr2026/head_efficient/attn_speed/flash-dmattn/build/temp.linux-x86_64-cpython-310/csrc/src/instantiations/flash_fwd_split_hdim64_fp16_sm80.o /workspace/cvpr2026/head_efficient/attn_speed/flash-dmattn/build/temp.linux-x86_64-cpython-310/csrc/src/instantiations/flash_fwd_split_hdim96_bf16_causal_sm80.o /workspace/cvpr2026/head_efficient/attn_speed/flash-dmattn/build/temp.linux-x86_64-cpython-310/csrc/src/instantiations/flash_fwd_split_hdim96_bf16_sm80.o /workspace/cvpr2026/head_efficient/attn_speed/flash-dmattn/build/temp.linux-x86_64-cpython-310/csrc/src/instantiations/flash_fwd_split_hdim96_fp16_causal_sm80.o /workspace/cvpr2026/head_efficient/attn_speed/flash-dmattn/build/temp.linux-x86_64-cpython-310/csrc/src/instantiations/flash_fwd_split_hdim96_fp16_sm80.o -L/venv/main/lib/python3.10/site-packages/torch/lib -L/usr/local/cuda-12.4/lib64 -lc10 -ltorch -ltorch_cpu -ltorch_python -lcudart -lc10_cuda -ltorch_cuda -o build/lib.linux-x86_64-cpython-310/flash_dmattn_cuda.cpython-310-x86_64-linux-gnu.so
  installing to build/bdist.linux-x86_64/wheel
  running install
  running install_lib
  creating build/bdist.linux-x86_64/wheel
  creating build/bdist.linux-x86_64/wheel/flash_dmattn
  creating build/bdist.linux-x86_64/wheel/flash_dmattn/integrations
  copying build/lib.linux-x86_64-cpython-310/flash_dmattn/integrations/flash_dynamic_mask_attention.py -> build/bdist.linux-x86_64/wheel/./flash_dmattn/integrations
  copying build/lib.linux-x86_64-cpython-310/flash_dmattn/integrations/import_utils.py -> build/bdist.linux-x86_64/wheel/./flash_dmattn/integrations
  copying build/lib.linux-x86_64-cpython-310/flash_dmattn/integrations/modeling_flash_dynamic_mask_attention_utils.py -> build/bdist.linux-x86_64/wheel/./flash_dmattn/integrations
  copying build/lib.linux-x86_64-cpython-310/flash_dmattn/__init__.py -> build/bdist.linux-x86_64/wheel/./flash_dmattn
  copying build/lib.linux-x86_64-cpython-310/flash_dmattn/flash_dmattn_flex.py -> build/bdist.linux-x86_64/wheel/./flash_dmattn
  copying build/lib.linux-x86_64-cpython-310/flash_dmattn/flash_dmattn_interface.py -> build/bdist.linux-x86_64/wheel/./flash_dmattn
  copying build/lib.linux-x86_64-cpython-310/flash_dmattn/flash_dmattn_triton.py -> build/bdist.linux-x86_64/wheel/./flash_dmattn
  copying build/lib.linux-x86_64-cpython-310/flash_dmattn_cuda.cpython-310-x86_64-linux-gnu.so -> build/bdist.linux-x86_64/wheel/.
  running install_egg_info
  Copying flash_dmattn.egg-info to build/bdist.linux-x86_64/wheel/./flash_dmattn-1.0.0-py3.10.egg-info
  running install_scripts
  creating build/bdist.linux-x86_64/wheel/flash_dmattn-1.0.0.dist-info/WHEEL
  creating '/tmp/pip-wheel-_aukau7n/.tmp-63wmuz54/flash_dmattn-1.0.0-cp310-cp310-linux_x86_64.whl' and adding 'build/bdist.linux-x86_64/wheel' to it
  adding 'flash_dmattn_cuda.cpython-310-x86_64-linux-gnu.so'
  adding 'flash_dmattn/__init__.py'
  adding 'flash_dmattn/flash_dmattn_flex.py'
  adding 'flash_dmattn/flash_dmattn_interface.py'
  adding 'flash_dmattn/flash_dmattn_triton.py'
  adding 'flash_dmattn/integrations/flash_dynamic_mask_attention.py'
  adding 'flash_dmattn/integrations/import_utils.py'
  adding 'flash_dmattn/integrations/modeling_flash_dynamic_mask_attention_utils.py'
  adding 'flash_dmattn-1.0.0.dist-info/licenses/AUTHORS'
  adding 'flash_dmattn-1.0.0.dist-info/licenses/LICENSE'
  adding 'flash_dmattn-1.0.0.dist-info/METADATA'
  adding 'flash_dmattn-1.0.0.dist-info/WHEEL'
  adding 'flash_dmattn-1.0.0.dist-info/top_level.txt'
  adding 'flash_dmattn-1.0.0.dist-info/RECORD'
  removing build/bdist.linux-x86_64/wheel
  Building wheel for flash-dmattn (pyproject.toml): finished with status 'done'
  Created wheel for flash-dmattn: filename=flash_dmattn-1.0.0-cp310-cp310-linux_x86_64.whl size=17827823 sha256=4c2d3d4451b41e4de8dfd21ed543c6144611bc5e29b234dc219d063d82375a55
  Stored in directory: /root/.cache/pip/wheels/0e/ab/b1/875252e544b45c1a1e4c306520bcd7b7d733fbb8d2c807442a
Successfully built flash-dmattn
Installing collected packages: flash-dmattn
  Attempting uninstall: flash-dmattn
    Found existing installation: flash-dmattn 1.0.0
    Uninstalling flash-dmattn-1.0.0:
      Removing file or directory /venv/main/lib/python3.10/site-packages/flash_dmattn-1.0.0.dist-info/
      Removing file or directory /venv/main/lib/python3.10/site-packages/flash_dmattn/__init__.py
      Removing file or directory /venv/main/lib/python3.10/site-packages/flash_dmattn/__pycache__/
      Removing file or directory /venv/main/lib/python3.10/site-packages/flash_dmattn/flash_dmattn_flex.py
      Removing file or directory /venv/main/lib/python3.10/site-packages/flash_dmattn/flash_dmattn_interface.py
      Removing file or directory /venv/main/lib/python3.10/site-packages/flash_dmattn/flash_dmattn_triton.py
      Removing file or directory /venv/main/lib/python3.10/site-packages/flash_dmattn/integrations/
      Removing file or directory /venv/main/lib/python3.10/site-packages/flash_dmattn_cuda.cpython-310-x86_64-linux-gnu.so
      Successfully uninstalled flash-dmattn-1.0.0
Successfully installed flash-dmattn-1.0.0
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager, possibly rendering your system unusable. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv. Use the --root-user-action option if you know what you are doing and want to suppress this warning.
`
This is my installation log, thanks for your help and looking forward to your reply

**Comment by LoserCheems** [comment]
> > Hi [@zylwithxy](https://github.com/zylwithxy), could you please post the installation log?
> > I suspect you might have encountered the same issue as [#149](https://github.com/SmallDoges/flash-dmattn/pull/149), but this problem has been fixed, You can try pulling the latest changes to give it a try.🤗
> 
> `Using pip 25.2 from /venv/main/lib/python3.10/site-packages/pip (python 3.10) Processing /workspace/cvpr2026/head_efficient/attn_speed/flash-dmattn Preparing metadata (pyproject.toml): started Running command Preparing metadata (pyproject.toml)
> 
> torch.**version** = 2.8.0+cu126
> 
> /venv/main/lib/python3.10/site-packages/setuptools/config/_apply_pyprojecttoml.py:82: SetuptoolsDeprecationWarning: as a TOML table is deprecated !!`project.license`
> 
> ```
>       ********************************************************************************
>       Please use a simple string containing a SPDX expression for `project.license`. You can also use `project.license-files`. (Both options available on setuptools>=77.0.0).
> 
>       By 2026-Feb-18, you need to update your project and remove deprecated calls
>       or your builds will no longer be supported.
> 
>       See https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#license for details.
>       ********************************************************************************
> ```
> 
> !! corresp(dist, value, root_dir) /venv/main/lib/python3.10/site-packages/setuptools/config/_apply_pyprojecttoml.py:61: SetuptoolsDeprecationWarning: License classifiers are deprecated. !!
> 
> ```
>       ********************************************************************************
>       Please consider removing the following classifiers in favor of a SPDX license expression:
> 
>       License :: OSI Approved :: BSD License
> 
>       See https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#license for details.
>       ********************************************************************************
> ```
> 
> !! dist._finalize_license_expression() /venv/main/lib/python3.10/site-packages/setuptools/dist.py:759: SetuptoolsDeprecationWarning: License classifiers are deprecated. !!
> 
> ```
>       ********************************************************************************
>       Please consider removing the following classifiers in favor of a SPDX license expression:
> 
>       License :: OSI Approved :: BSD License
> 
>       See https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#license for details.
>       ********************************************************************************
> ```
> 
> !! self._finalize_license_expression() running dist_info creating /tmp/pip-modern-metadata-1e4ka6ds/flash_dmattn.egg-info writing /tmp/pip-modern-metadata-1e4ka6ds/flash_dmattn.egg-info/PKG-INFO writing dependency_links to /tmp/pip-modern-metadata-1e4ka6ds/flash_dmattn.egg-info/dependency_links.txt writing requirements to /tmp/pip-modern-metadata-1e4ka6ds/flash_dmattn.egg-info/requires.txt writing top-level names to /tmp/pip-modern-metadata-1e4ka6ds/flash_dmattn.egg-info/top_level.txt writing manifest file '/tmp/pip-modern-metadata-1e4ka6ds/flash_dmattn.egg-info/SOURCES.txt' reading manifest file '/tmp/pip-modern-metadata-1e4ka6ds/flash_dmattn.egg-info/SOURCES.txt' reading manifest template 'MANIFEST.in' warning: no files found matching '_.cu' under directory 'src' warning: no files found matching '_.h' under directory 'src' warning: no files found matching '_.cuh' under directory 'src' warning: no files found matching '_.cpp' under directory 'src' warning: no files found matching '*.hpp' under directory 'src' adding license file 'LICENSE' adding license file 'AUTHORS' writing manifest file '/tmp/pip-modern-metadata-1e4ka6ds/flash_dmattn.egg-info/SOURCES.txt' creating '/tmp/pip-modern-metadata-1e4ka6ds/flash_dmattn-1.0.0.dist-info' Preparing metadata (pyproject.toml): finished with status 'done' Requirement already satisfied: torch in /venv/main/lib/python3.10/site-packages (from flash-dmattn==1.0.0) (2.8.0+cu126) Requirement already satisfied: einops in /venv/main/lib/python3.10/site-packages (from flash-dmattn==1.0.0) (0.8.1) Requirement already satisfied: filelock in /venv/main/lib/python3.10/site-packages (from torch->flash-dmattn==1.0.0) (3.18.0) Requirement already satisfied: typing-extensions>=4.10.0 in /venv/main/lib/python3.10/site-packages (from torch->flash-dmattn==1.0.0) (4.14.0) Requirement already satisfied: sympy>=1.13.3 in /venv/main/lib/python3.10/site-packages (from torch->flash-dmattn==1.0.0) (1.13.3) Requirement already satisfied: networkx in /venv/main/lib/python3.10/site-packages (from torch->flash-dmattn==1.0.0) (3.3) Requirement already satisfied: jinja2 in /venv/main/lib/python3.10/site-packages (from torch->flash-dmattn==1.0.0) (3.1.4) Requirement already satisfied: fsspec in /venv/main/lib/python3.10/site-packages (from torch->flash-dmattn==1.0.0) (2025.5.1) Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.6.77 in /venv/main/lib/python3.10/site-packages (from torch->flash-dmattn==1.0.0) (12.6.77) Requirement already satisfied: nvidia-cuda-runtime-cu12==12.6.77 in /venv/main/lib/python3.10/site-packages (from torch->flash-dmattn==1.0.0) (12.6.77) Requirement already satisfied: nvidia-cuda-cupti-cu12==12.6.80 in /venv/main/lib/python3.10/site-packages (from torch->flash-dmattn==1.0.0) (12.6.80) Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /venv/main/lib/python3.10/site-packages (from torch->flash-dmattn==1.0.0) (9.10.2.21) Requirement already satisfied: nvidia-cublas-cu12==12.6.4.1 in /venv/main/lib/python3.10/site-packages (from torch->flash-dmattn==1.0.0) (12.6.4.1) Requirement already satisfied: nvidia-cufft-cu12==11.3.0.4 in /venv/main/lib/python3.10/site-packages (from torch->flash-dmattn==1.0.0) (11.3.0.4) Requirement already satisfied: nvidia-curand-cu12==10.3.7.77 in /venv/main/lib/python3.10/site-packages (from torch->flash-dmattn==1.0.0) (10.3.7.77) Requirement already satisfied: nvidia-cusolver-cu12==11.7.1.2 in /venv/main/lib/python3.10/site-packages (from torch->flash-dmattn==1.0.0) (11.7.1.2) Requirement already satisfied: nvidia-cusparse-cu12==12.5.4.2 in /venv/main/lib/python3.10/site-packages (from torch->flash-dmattn==1.0.0) (12.5.4.2) Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /venv/main/lib/python3.10/site-packages (from torch->flash-dmattn==1.0.0) (0.7.1) Requirement already satisfied: nvidia-nccl-cu12==2.27.3 in /venv/main/lib/python3.10/site-packages (from torch->flash-dmattn==1.0.0) (2.27.3) Requirement already satisfied: nvidia-nvtx-cu12==12.6.77 in /venv/main/lib/python3.10/site-packages (from torch->flash-dmattn==1.0.0) (12.6.77) Requirement already satisfied: nvidia-nvjitlink-cu12==12.6.85 in /venv/main/lib/python3.10/site-packages (from torch->flash-dmattn==1.0.0) (12.6.85) Requirement already satisfied: nvidia-cufile-cu12==1.11.1.6 in /venv/main/lib/python3.10/site-packages (from torch->flash-dmattn==1.0.0) (1.11.1.6) Requirement already satisfied: triton==3.4.0 in /venv/main/lib/python3.10/site-packages (from torch->flash-dmattn==1.0.0) (3.4.0) Requirement already satisfied: setuptools>=40.8.0 in /venv/main/lib/python3.10/site-packages (from triton==3.4.0->torch->flash-dmattn==1.0.0) (80.9.0) Requirement already satisfied: mpmath<1.4,>=1.1.0 in /venv/main/lib/python3.10/site-packages (from sympy>=1.13.3->torch->flash-dmattn==1.0.0) (1.3.0) Requirement already satisfied: MarkupSafe>=2.0 in /venv/main/lib/python3.10/site-packages (from jinja2->torch->flash-dmattn==1.0.0) (2.1.5) Building wheels for collected packages: flash-dmattn Building wheel for flash-dmattn (pyproject.toml): started Running command Building wheel for flash-dmattn (pyproject.toml)
> 
> torch.**version** = 2.8.0+cu126
> 
> /venv/main/lib/python3.10/site-packages/setuptools/config/_apply_pyprojecttoml.py:82: SetuptoolsDeprecationWarning: as a TOML table is deprecated !!`project.license`
> 
> ```
>       ********************************************************************************
>       Please use a simple string containing a SPDX expression for `project.license`. You can also use `project.license-files`. (Both options available on setuptools>=77.0.0).
> 
>       By 2026-Feb-18, you need to update your project and remove deprecated calls
>       or your builds will no longer be supported.
> 
>       See https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#license for details.
>       ********************************************************************************
> ```
> 
> !! corresp(dist, value, root_dir) /venv/main/lib/python3.10/site-packages/setuptools/config/_apply_pyprojecttoml.py:61: SetuptoolsDeprecationWarning: License classifiers are deprecated. !!
> 
> ```
>       ********************************************************************************
>       Please consider removing the following classifiers in favor of a SPDX license expression:
> 
>       License :: OSI Approved :: BSD License
> 
>       See https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#license for details.
>       ********************************************************************************
> ```
> 
> !! dist._finalize_license_expression() /venv/main/lib/python3.10/site-packages/setuptools/dist.py:759: SetuptoolsDeprecationWarning: License classifiers are deprecated. !!
> 
> ```
>       ********************************************************************************
>       Please consider removing the following classifiers in favor of a SPDX license expression:
> 
>       License :: OSI Approved :: BSD License
> 
>       See https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#license for details.
>       ********************************************************************************
> ```
> 
> !! self._finalize_license_expression() running bdist_wheel running build running build_py copying flash_dmattn/**init**.py -> build/lib.linux-x86_64-cpython-310/flash_dmattn copying flash_dmattn/flash_dmattn_flex.py -> build/lib.linux-x86_64-cpython-310/flash_dmattn copying flash_dmattn/flash_dmattn_interface.py -> build/lib.linux-x86_64-cpython-310/flash_dmattn copying flash_dmattn/flash_dmattn_triton.py -> build/lib.linux-x86_64-cpython-310/flash_dmattn copying flash_dmattn/integrations/flash_dynamic_mask_attention.py -> build/lib.linux-x86_64-cpython-310/flash_dmattn/integrations copying flash_dmattn/integrations/import_utils.py -> build/lib.linux-x86_64-cpython-310/flash_dmattn/integrations copying flash_dmattn/integrations/modeling_flash_dynamic_mask_attention_utils.py -> build/lib.linux-x86_64-cpython-310/flash_dmattn/integrations running egg_info writing flash_dmattn.egg-info/PKG-INFO writing dependency_links to flash_dmattn.egg-info/dependency_links.txt writing requirements to flash_dmattn.egg-info/requires.txt writing top-level names to flash_dmattn.egg-info/top_level.txt reading manifest file 'flash_dmattn.egg-info/SOURCES.txt' reading manifest template 'MANIFEST.in' warning: no files found matching '_.cu' under directory 'src' warning: no files found matching '_.h' under directory 'src' warning: no files found matching '_.cuh' under directory 'src' warning: no files found matching '_.cpp' under directory 'src' warning: no files found matching '*.hpp' under directory 'src' adding license file 'LICENSE' adding license file 'AUTHORS' writing manifest file 'flash_dmattn.egg-info/SOURCES.txt' copying flash_dmattn/**init**.py -> build/lib.linux-x86_64-cpython-310/flash_dmattn copying flash_dmattn/flash_dmattn_flex.py -> build/lib.linux-x86_64-cpython-310/flash_dmattn copying flash_dmattn/flash_dmattn_interface.py -> build/lib.linux-x86_64-cpython-310/flash_dmattn copying flash_dmattn/flash_dmattn_triton.py -> build/lib.linux-x86_64-cpython-310/flash_dmattn running build_ext W0906 08:17:11.737000 4707 site-packages/torch/utils/cpp_extension.py:507] The detected CUDA version (12.4) has a minor version mismatch with the version that was used to compile PyTorch (12.6). Most likely this shouldn't be a problem. W0906 08:17:11.738000 4707 site-packages/torch/utils/cpp_extension.py:517] There are no g++ version bounds defined for CUDA version 12.4 building 'flash_dmattn_cuda' extension ninja: no work to do. g++ -pthread -B /venv/main/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /venv/main/include -fPIC -O2 -isystem /venv/main/include -shared /workspace/cvpr2026/head_efficient/attn_speed/flash-dmattn/build/temp.linux-x86_64-cpython-310/csrc/flash_api.o /workspace/cvpr2026/head_efficient/attn_speed/flash-dmattn/build/temp.linux-x86_64-cpython-310/csrc/src/instantiations/flash_bwd_hdim128_bf16_causal_sm80.o /workspace/cvpr2026/head_efficient/attn_speed/flash-dmattn/build/temp.linux-x86_64-cpython-310/csrc/src/instantiations/flash_bwd_hdim128_bf16_sm80.o /workspace/cvpr2026/head_efficient/attn_speed/flash-dmattn/build/temp.linux-x86_64-cpython-310/csrc/src/instantiations/flash_bwd_hdim128_fp16_causal_sm80.o /workspace/cvpr2026/head_efficient/attn_speed/flash-dmattn/build/temp.linux-x86_64-cpython-310/csrc/src/instantiations/flash_bwd_hdim128_fp16_sm80.o /workspace/cvpr2026/head_efficient/attn_speed/flash-dmattn/build/temp.linux-x86_64-cpython-310/csrc/src/instantiations/flash_bwd_hdim192_bf16_causal_sm80.o /workspace/cvpr2026/head_efficient/attn_speed/flash-dmattn/build/temp.linux-x86_64-cpython-310/csrc/src/instantiations/flash_bwd_hdim192_bf16_sm80.o /workspace/cvpr2026/head_efficient/attn_speed/flash-dmattn/build/temp.linux-x86_64-cpython-310/csrc/src/instantiations/flash_bwd_hdim192_fp16_causal_sm80.o /workspace/cvpr2026/head_efficient/attn_speed/flash-dmattn/build/temp.linux-x86_64-cpython-310/csrc/src/instantiations/flash_bwd_hdim192_fp16_sm80.o /workspace/cvpr2026/head_efficient/attn_speed/flash-dmattn/build/temp.linux-x86_64-cpython-310/csrc/src/instantiations/flash_bwd_hdim256_bf16_causal_sm80.o /workspace/cvpr2026/head_efficient/attn_speed/flash-dmattn/build/temp.linux-x86_64-cpython-310/csrc/src/instantiations/flash_bwd_hdim256_bf16_sm80.o /workspace/cvpr2026/head_efficient/attn_speed/flash-dmattn/build/temp.linux-x86_64-cpython-310/csrc/src/instantiations/flash_bwd_hdim256_fp16_causal_sm80.o /workspace/cvpr2026/head_efficient/attn_speed/flash-dmattn/build/temp.linux-x86_64-cpython-310/csrc/src/instantiations/flash_bwd_hdim256_fp16_sm80.o /workspace/cvpr2026/head_efficient/attn_speed/flash-dmattn/build/temp.linux-x86_64-cpython-310/csrc/src/instantiations/flash_bwd_hdim32_bf16_causal_sm80.o /workspace/cvpr2026/head_efficient/attn_speed/flash-dmattn/build/temp.linux-x86_64-cpython-310/csrc/src/instantiations/flash_bwd_hdim32_bf16_sm80.o /workspace/cvpr2026/head_efficient/attn_speed/flash-dmattn/build/temp.linux-x86_64-cpython-310/csrc/src/instantiations/flash_bwd_hdim32_fp16_causal_sm80.o /workspace/cvpr2026/head_efficient/attn_speed/flash-dmattn/build/temp.linux-x86_64-cpython-310/csrc/src/instantiations/flash_bwd_hdim32_fp16_sm80.o /workspace/cvpr2026/head_efficient/attn_speed/flash-dmattn/build/temp.linux-x86_64-cpython-310/csrc/src/instantiations/flash_bwd_hdim64_bf16_causal_sm80.o /workspace/cvpr2026/head_efficient/attn_speed/flash-dmattn/build/temp.linux-x86_64-cpython-310/csrc/src/instantiations/flash_bwd_hdim64_bf16_sm80.o /workspace/cvpr2026/head_efficient/attn_speed/flash-dmattn/build/temp.linux-x86_64-cpython-310/csrc/src/instantiations/flash_bwd_hdim64_fp16_causal_sm80.o /workspace/cvpr2026/head_efficient/attn_speed/flash-dmattn/build/temp.linux-x86_64-cpython-310/csrc/src/instantiations/flash_bwd_hdim64_fp16_sm80.o /workspace/cvpr2026/head_efficient/attn_speed/flash-dmattn/build/temp.linux-x86_64-cpython-310/csrc/src/instantiations/flash_bwd_hdim96_bf16_causal_sm80.o /workspace/cvpr2026/head_efficient/attn_speed/flash-dmattn/build/temp.linux-x86_64-cpython-310/csrc/src/instantiations/flash_bwd_hdim96_bf16_sm80.o /workspace/cvpr2026/head_efficient/attn_speed/flash-dmattn/build/temp.linux-x86_64-cpython-310/csrc/src/instantiations/flash_bwd_hdim96_fp16_causal_sm80.o /workspace/cvpr2026/head_efficient/attn_speed/flash-dmattn/build/temp.linux-x86_64-cpython-310/csrc/src/instantiations/flash_bwd_hdim96_fp16_sm80.o /workspace/cvpr2026/head_efficient/attn_speed/flash-dmattn/build/temp.linux-x86_64-cpython-310/csrc/src/instantiations/flash_fwd_hdim128_bf16_causal_sm80.o /workspace/cvpr2026/head_efficient/attn_speed/flash-dmattn/build/temp.linux-x86_64-cpython-310/csrc/src/instantiations/flash_fwd_hdim128_bf16_sm80.o /workspace/cvpr2026/head_efficient/attn_speed/flash-dmattn/build/temp.linux-x86_64-cpython-310/csrc/src/instantiations/flash_fwd_hdim128_fp16_causal_sm80.o /workspace/cvpr2026/head_efficient/attn_speed/flash-dmattn/build/temp.linux-x86_64-cpython-310/csrc/src/instantiations/flash_fwd_hdim128_fp16_sm80.o /workspace/cvpr2026/head_efficient/attn_speed/flash-dmattn/build/temp.linux-x86_64-cpython-310/csrc/src/instantiations/flash_fwd_hdim192_bf16_causal_sm80.o /workspace/cvpr2026/head_efficient/attn_speed/flash-dmattn/build/temp.linux-x86_64-cpython-310/csrc/src/instantiations/flash_fwd_hdim192_bf16_sm80.o /workspace/cvpr2026/head_efficient/attn_speed/flash-dmattn/build/temp.linux-x86_64-cpython-310/csrc/src/instantiations/flash_fwd_hdim192_fp16_causal_sm80.o /workspace/cvpr2026/head_efficient/attn_speed/flash-dmattn/build/temp.linux-x86_64-cpython-310/csrc/src/instantiations/flash_fwd_hdim192_fp16_sm80.o /workspace/cvpr2026/head_efficient/attn_speed/flash-dmattn/build/temp.linux-x86_64-cpython-310/csrc/src/instantiations/flash_fwd_hdim256_bf16_causal_sm80.o /workspace/cvpr2026/head_efficient/attn_speed/flash-dmattn/build/temp.linux-x86_64-cpython-310/csrc/src/instantiations/flash_fwd_hdim256_bf16_sm80.o /workspace/cvpr2026/head_efficient/attn_speed/flash-dmattn/build/temp.linux-x86_64-cpython-310/csrc/src/instantiations/flash_fwd_hdim256_fp16_causal_sm80.o /workspace/cvpr2026/head_efficient/attn_speed/flash-dmattn/build/temp.linux-x86_64-cpython-310/csrc/src/instantiations/flash_fwd_hdim256_fp16_sm80.o /workspace/cvpr2026/head_efficient/attn_speed/flash-dmattn/build/temp.linux-x86_64-cpython-310/csrc/src/instantiations/flash_fwd_hdim32_bf16_causal_sm80.o /workspace/cvpr2026/head_efficient/attn_speed/flash-dmattn/build/temp.linux-x86_64-cpython-310/csrc/src/instantiations/flash_fwd_hdim32_bf16_sm80.o /workspace/cvpr2026/head_efficient/attn_speed/flash-dmattn/build/temp.linux-x86_64-cpython-310/csrc/src/instantiations/flash_fwd_hdim32_fp16_causal_sm80.o /workspace/cvpr2026/head_efficient/attn_speed/flash-dmattn/build/temp.linux-x86_64-cpython-310/csrc/src/instantiations/flash_fwd_hdim32_fp16_sm80.o /workspace/cvpr2026/head_efficient/attn_speed/flash-dmattn/build/temp.linux-x86_64-cpython-310/csrc/src/instantiations/flash_fwd_hdim64_bf16_causal_sm80.o /workspace/cvpr2026/head_efficient/attn_speed/flash-dmattn/build/temp.linux-x86_64-cpython-310/csrc/src/instantiations/flash_fwd_hdim64_bf16_sm80.o /workspace/cvpr2026/head_efficient/attn_speed/flash-dmattn/build/temp.linux-x86_64-cpython-310/csrc/src/instantiations/flash_fwd_hdim64_fp16_causal_sm80.o /workspace/cvpr2026/head_efficient/attn_speed/flash-dmattn/build/temp.linux-x86_64-cpython-310/csrc/src/instantiations/flash_fwd_hdim64_fp16_sm80.o /workspace/cvpr2026/head_efficient/attn_speed/flash-dmattn/build/temp.linux-x86_64-cpython-310/csrc/src/instantiations/flash_fwd_hdim96_bf16_causal_sm80.o /workspace/cvpr2026/head_efficient/attn_speed/flash-dmattn/build/temp.linux-x86_64-cpython-310/csrc/src/instantiations/flash_fwd_hdim96_bf16_sm80.o /workspace/cvpr2026/head_efficient/attn_speed/flash-dmattn/build/temp.linux-x86_64-cpython-310/csrc/src/instantiations/flash_fwd_hdim96_fp16_causal_sm80.o /workspace/cvpr2026/head_efficient/attn_speed/flash-dmattn/build/temp.linux-x86_64-cpython-310/csrc/src/instantiations/flash_fwd_hdim96_fp16_sm80.o /workspace/cvpr2026/head_efficient/attn_speed/flash-dmattn/build/temp.linux-x86_64-cpython-310/csrc/src/instantiations/flash_fwd_split_hdim128_bf16_causal_sm80.o /workspace/cvpr2026/head_efficient/attn_speed/flash-dmattn/build/temp.linux-x86_64-cpython-310/csrc/src/instantiations/flash_fwd_split_hdim128_bf16_sm80.o /workspace/cvpr2026/head_efficient/attn_speed/flash-dmattn/build/temp.linux-x86_64-cpython-310/csrc/src/instantiations/flash_fwd_split_hdim128_fp16_causal_sm80.o /workspace/cvpr2026/head_efficient/attn_speed/flash-dmattn/build/temp.linux-x86_64-cpython-310/csrc/src/instantiations/flash_fwd_split_hdim128_fp16_sm80.o /workspace/cvpr2026/head_efficient/attn_speed/flash-dmattn/build/temp.linux-x86_64-cpython-310/csrc/src/instantiations/flash_fwd_split_hdim192_bf16_causal_sm80.o /workspace/cvpr2026/head_efficient/attn_speed/flash-dmattn/build/temp.linux-x86_64-cpython-310/csrc/src/instantiations/flash_fwd_split_hdim192_bf16_sm80.o /workspace/cvpr2026/head_efficient/attn_speed/flash-dmattn/build/temp.linux-x86_64-cpython-310/csrc/src/instantiations/flash_fwd_split_hdim192_fp16_causal_sm80.o /workspace/cvpr2026/head_efficient/attn_speed/flash-dmattn/build/temp.linux-x86_64-cpython-310/csrc/src/instantiations/flash_fwd_split_hdim192_fp16_sm80.o /workspace/cvpr2026/head_efficient/attn_speed/flash-dmattn/build/temp.linux-x86_64-cpython-310/csrc/src/instantiations/flash_fwd_split_hdim256_bf16_causal_sm80.o /workspace/cvpr2026/head_efficient/attn_speed/flash-dmattn/build/temp.linux-x86_64-cpython-310/csrc/src/instantiations/flash_fwd_split_hdim256_bf16_sm80.o /workspace/cvpr2026/head_efficient/attn_speed/flash-dmattn/build/temp.linux-x86_64-cpython-310/csrc/src/instantiations/flash_fwd_split_hdim256_fp16_causal_sm80.o /workspace/cvpr2026/head_efficient/attn_speed/flash-dmattn/build/temp.linux-x86_64-cpython-310/csrc/src/instantiations/flash_fwd_split_hdim256_fp16_sm80.o /workspace/cvpr2026/head_efficient/attn_speed/flash-dmattn/build/temp.linux-x86_64-cpython-310/csrc/src/instantiations/flash_fwd_split_hdim32_bf16_causal_sm80.o /workspace/cvpr2026/head_efficient/attn_speed/flash-dmattn/build/temp.linux-x86_64-cpython-310/csrc/src/instantiations/flash_fwd_split_hdim32_bf16_sm80.o /workspace/cvpr2026/head_efficient/attn_speed/flash-dmattn/build/temp.linux-x86_64-cpython-310/csrc/src/instantiations/flash_fwd_split_hdim32_fp16_causal_sm80.o /workspace/cvpr2026/head_efficient/attn_speed/flash-dmattn/build/temp.linux-x86_64-cpython-310/csrc/src/instantiations/flash_fwd_split_hdim32_fp16_sm80.o /workspace/cvpr2026/head_efficient/attn_speed/flash-dmattn/build/temp.linux-x86_64-cpython-310/csrc/src/instantiations/flash_fwd_split_hdim64_bf16_causal_sm80.o /workspace/cvpr2026/head_efficient/attn_speed/flash-dmattn/build/temp.linux-x86_64-cpython-310/csrc/src/instantiations/flash_fwd_split_hdim64_bf16_sm80.o /workspace/cvpr2026/head_efficient/attn_speed/flash-dmattn/build/temp.linux-x86_64-cpython-310/csrc/src/instantiations/flash_fwd_split_hdim64_fp16_causal_sm80.o /workspace/cvpr2026/head_efficient/attn_speed/flash-dmattn/build/temp.linux-x86_64-cpython-310/csrc/src/instantiations/flash_fwd_split_hdim64_fp16_sm80.o /workspace/cvpr2026/head_efficient/attn_speed/flash-dmattn/build/temp.linux-x86_64-cpython-310/csrc/src/instantiations/flash_fwd_split_hdim96_bf16_causal_sm80.o /workspace/cvpr2026/head_efficient/attn_speed/flash-dmattn/build/temp.linux-x86_64-cpython-310/csrc/src/instantiations/flash_fwd_split_hdim96_bf16_sm80.o /workspace/cvpr2026/head_efficient/attn_speed/flash-dmattn/build/temp.linux-x86_64-cpython-310/csrc/src/instantiations/flash_fwd_split_hdim96_fp16_causal_sm80.o /workspace/cvpr2026/head_efficient/attn_speed/flash-dmattn/build/temp.linux-x86_64-cpython-310/csrc/src/instantiations/flash_fwd_split_hdim96_fp16_sm80.o -L/venv/main/lib/python3.10/site-packages/torch/lib -L/usr/local/cuda-12.4/lib64 -lc10 -ltorch -ltorch_cpu -ltorch_python -lcudart -lc10_cuda -ltorch_cuda -o build/lib.linux-x86_64-cpython-310/flash_dmattn_cuda.cpython-310-x86_64-linux-gnu.so installing to build/bdist.linux-x86_64/wheel running install running install_lib creating build/bdist.linux-x86_64/wheel creating build/bdist.linux-x86_64/wheel/flash_dmattn creating build/bdist.linux-x86_64/wheel/flash_dmattn/integrations copying build/lib.linux-x86_64-cpython-310/flash_dmattn/integrations/flash_dynamic_mask_attention.py -> build/bdist.linux-x86_64/wheel/./flash_dmattn/integrations copying build/lib.linux-x86_64-cpython-310/flash_dmattn/integrations/import_utils.py -> build/bdist.linux-x86_64/wheel/./flash_dmattn/integrations copying build/lib.linux-x86_64-cpython-310/flash_dmattn/integrations/modeling_flash_dynamic_mask_attention_utils.py -> build/bdist.linux-x86_64/wheel/./flash_dmattn/integrations copying build/lib.linux-x86_64-cpython-310/flash_dmattn/**init**.py -> build/bdist.linux-x86_64/wheel/./flash_dmattn copying build/lib.linux-x86_64-cpython-310/flash_dmattn/flash_dmattn_flex.py -> build/bdist.linux-x86_64/wheel/./flash_dmattn copying build/lib.linux-x86_64-cpython-310/flash_dmattn/flash_dmattn_interface.py -> build/bdist.linux-x86_64/wheel/./flash_dmattn copying build/lib.linux-x86_64-cpython-310/flash_dmattn/flash_dmattn_triton.py -> build/bdist.linux-x86_64/wheel/./flash_dmattn copying build/lib.linux-x86_64-cpython-310/flash_dmattn_cuda.cpython-310-x86_64-linux-gnu.so -> build/bdist.linux-x86_64/wheel/. running install_egg_info Copying flash_dmattn.egg-info to build/bdist.linux-x86_64/wheel/./flash_dmattn-1.0.0-py3.10.egg-info running install_scripts creating build/bdist.linux-x86_64/wheel/flash_dmattn-1.0.0.dist-info/WHEEL creating '/tmp/pip-wheel-_aukau7n/.tmp-63wmuz54/flash_dmattn-1.0.0-cp310-cp310-linux_x86_64.whl' and adding 'build/bdist.linux-x86_64/wheel' to it adding 'flash_dmattn_cuda.cpython-310-x86_64-linux-gnu.so' adding 'flash_dmattn/**init**.py' adding 'flash_dmattn/flash_dmattn_flex.py' adding 'flash_dmattn/flash_dmattn_interface.py' adding 'flash_dmattn/flash_dmattn_triton.py' adding 'flash_dmattn/integrations/flash_dynamic_mask_attention.py' adding 'flash_dmattn/integrations/import_utils.py' adding 'flash_dmattn/integrations/modeling_flash_dynamic_mask_attention_utils.py' adding 'flash_dmattn-1.0.0.dist-info/licenses/AUTHORS' adding 'flash_dmattn-1.0.0.dist-info/licenses/LICENSE' adding 'flash_dmattn-1.0.0.dist-info/METADATA' adding 'flash_dmattn-1.0.0.dist-info/WHEEL' adding 'flash_dmattn-1.0.0.dist-info/top_level.txt' adding 'flash_dmattn-1.0.0.dist-info/RECORD' removing build/bdist.linux-x86_64/wheel Building wheel for flash-dmattn (pyproject.toml): finished with status 'done' Created wheel for flash-dmattn: filename=flash_dmattn-1.0.0-cp310-cp310-linux_x86_64.whl size=17827823 sha256=4c2d3d4451b41e4de8dfd21ed543c6144611bc5e29b234dc219d063d82375a55 Stored in directory: /root/.cache/pip/wheels/0e/ab/b1/875252e544b45c1a1e4c306520bcd7b7d733fbb8d2c807442a Successfully built flash-dmattn Installing collected packages: flash-dmattn Attempting uninstall: flash-dmattn Found existing installation: flash-dmattn 1.0.0 Uninstalling flash-dmattn-1.0.0: Removing file or directory /venv/main/lib/python3.10/site-packages/flash_dmattn-1.0.0.dist-info/ Removing file or directory /venv/main/lib/python3.10/site-packages/flash_dmattn/**init**.py Removing file or directory /venv/main/lib/python3.10/site-packages/flash_dmattn/**pycache**/ Removing file or directory /venv/main/lib/python3.10/site-packages/flash_dmattn/flash_dmattn_flex.py Removing file or directory /venv/main/lib/python3.10/site-packages/flash_dmattn/flash_dmattn_interface.py Removing file or directory /venv/main/lib/python3.10/site-packages/flash_dmattn/flash_dmattn_triton.py Removing file or directory /venv/main/lib/python3.10/site-packages/flash_dmattn/integrations/ Removing file or directory /venv/main/lib/python3.10/site-packages/flash_dmattn_cuda.cpython-310-x86_64-linux-gnu.so Successfully uninstalled flash-dmattn-1.0.0 Successfully installed flash-dmattn-1.0.0 WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager, possibly rendering your system unusable. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv. Use the --root-user-action option if you know what you are doing and want to suppress this warning. ` This is my installation log, thanks for your help and looking forward to your reply

There is no problem. You have successfully installed it. Could you please repost the run log?

**Comment by zylwithxy** [comment]
@LoserCheems Here is my run log, the problem still exists after I reinstall it.

<img width="770" height="97" alt="Image" src="https://github.com/user-attachments/assets/71c72337-6728-4acf-8dcc-f64088bb46cb" />

**Comment by zylwithxy** [comment]
@LoserCheems Here is my run log. I ran into a new problem.

<img width="775" height="137" alt="Image" src="https://github.com/user-attachments/assets/67b24351-3c5f-481b-846a-10b045a9a158" />

**Comment by LoserCheems** [comment]
@zylwithxy, could you please run the following command and paste the log here?

```bash
python benchmarks/forward_performance.py --test-type sdpa-vs-cuda
```

I'll take a look to see
